import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.orders': 'Órdenes',
    'nav.newOrder': 'Nueva Orden',
    'nav.myOrders': 'Mis Órdenes',
    'nav.negotiation': 'Negociación',
    'nav.deliveries': 'Entregas',
    'nav.providers': 'Proveedores',
    'nav.users': 'Usuarios',
    // Providers page
    'providers.title': 'Gestión de Proveedores',
    'providers.subtitle': 'Administra los proveedores y sus transacciones',
    'providers.new': 'Nuevo Proveedor',
    'providers.edit': 'Editar Proveedor',
    'providers.create': 'Crear Nuevo Proveedor',
    'providers.editDesc': 'Modifica los datos del proveedor.',
    'providers.createDesc': 'Completa los datos para registrar un nuevo proveedor.',
    'providers.name': 'Nombre del Proveedor',
    'providers.namePlaceholder': 'Ej: Minera San Rafael',
    'providers.email': 'Correo Electrónico',
    'providers.emailPlaceholder': 'correo@ejemplo.com',
    'providers.updated': 'Proveedor actualizado',
    'providers.updatedDesc': 'ha sido actualizado correctamente.',
    'providers.created': 'Proveedor creado',
    'providers.createdDesc': 'ha sido registrado correctamente.',
    'providers.deleted': 'Proveedor eliminado',
    'providers.deletedDesc': 'ha sido eliminado correctamente.',
    'providers.totalProviders': 'Total Proveedores',
    'providers.totalOrders': 'Total Pedidos',
    'providers.totalBalance': 'Saldo Total',
    'providers.list': 'Lista de Proveedores',
    'providers.listDesc': 'Todos los proveedores registrados en el sistema',
    'providers.search': 'Buscar por nombre o correo...',
    'providers.provider': 'Proveedor',
    'providers.orders': 'Pedidos',
    'providers.deliveries': 'Entregas',
    'providers.balance': 'Saldo',
    'providers.actions': 'Acciones',
    'providers.noResults': 'No se encontraron proveedores',
    'nav.reports': 'Reportes',
    'nav.settings': 'Configuración',
    'nav.logout': 'Cerrar Sesión',
    
    // Settings
    'settings.title': 'Configuración',
    'settings.subtitle': 'Administra las preferencias de tu cuenta y del sistema',
    'settings.profile': 'Perfil',
    'settings.notifications': 'Notificaciones',
    'settings.api': 'APIs',
    'settings.security': 'Seguridad',
    'settings.language': 'Idioma',
    
    // Profile
    'profile.title': 'Información del Perfil',
    'profile.description': 'Actualiza tu información personal y de contacto',
    'profile.fullName': 'Nombre Completo',
    'profile.email': 'Correo Electrónico',
    'profile.company': 'Empresa',
    'profile.phone': 'Teléfono',
    'profile.save': 'Guardar Cambios',
    'profile.updated': 'Perfil actualizado',
    'profile.updatedDesc': 'Los cambios han sido guardados correctamente.',
    
    // Notifications
    'notifications.title': 'Preferencias de Notificaciones',
    'notifications.description': 'Configura cómo y cuándo recibir notificaciones',
    'notifications.email': 'Notificaciones por Email',
    'notifications.push': 'Notificaciones Push',
    'notifications.newOrders': 'Nuevas órdenes',
    'notifications.newOrdersDesc': 'Recibe un email cuando se genere una nueva orden',
    'notifications.deliveries': 'Entregas registradas',
    'notifications.deliveriesDesc': 'Notificación cuando se registre una entrega',
    'notifications.weeklyReports': 'Reportes semanales',
    'notifications.weeklyReportsDesc': 'Resumen semanal de actividad',
    'notifications.orderAlerts': 'Alertas de órdenes',
    'notifications.orderAlertsDesc': 'Notificaciones en tiempo real de órdenes',
    'notifications.deliveryAlerts': 'Alertas de entregas',
    'notifications.deliveryAlertsDesc': 'Notificaciones en tiempo real de entregas',
    'notifications.save': 'Guardar Preferencias',
    'notifications.updated': 'Notificaciones actualizadas',
    'notifications.updatedDesc': 'Tus preferencias de notificación han sido guardadas.',
    
    // API
    'api.title': 'Configuración de APIs',
    'api.description': 'Gestiona las credenciales para las APIs de precios en vivo',
    'api.goldKey': 'API Key - Precio del Oro',
    'api.goldKeyPlaceholder': 'Tu API key de GoldAPI',
    'api.goldKeyHelp': 'Obtenla en goldapi.io',
    'api.dollarKey': 'API Key - Tasa de Cambio',
    'api.dollarKeyPlaceholder': 'Tu API key de ExchangeRate',
    'api.dollarKeyHelp': 'Obtenla en exchangerate-api.com',
    'api.refreshInterval': 'Intervalo de actualización (segundos)',
    'api.refreshIntervalHelp': 'Frecuencia de actualización de precios (mín: 10s)',
    'api.testConnection': 'Probar Conexión',
    'api.save': 'Guardar APIs',
    'api.saved': 'Configuración de API guardada',
    'api.savedDesc': 'Las credenciales de API han sido actualizadas.',
    
    // Security
    'security.title': 'Seguridad de la Cuenta',
    'security.description': 'Gestiona la seguridad y acceso a tu cuenta',
    'security.changePassword': 'Cambiar Contraseña',
    'security.currentPassword': 'Contraseña Actual',
    'security.newPassword': 'Nueva Contraseña',
    'security.confirmPassword': 'Confirmar Contraseña',
    'security.activeSessions': 'Sesiones Activas',
    'security.currentSession': 'Sesión actual',
    'security.location': 'Chrome en Windows • Bogotá, Colombia',
    'security.active': 'Activa',
    'security.updatePassword': 'Actualizar Contraseña',
    
    // Language
    'language.title': 'Preferencias de Idioma',
    'language.description': 'Selecciona el idioma de la interfaz',
    'language.select': 'Idioma de la interfaz',
    'language.spanish': 'Español',
    'language.english': 'Inglés',
    'language.save': 'Guardar Idioma',
    'language.saved': 'Idioma actualizado',
    'language.savedDesc': 'El idioma de la interfaz ha sido cambiado.',
    
    // Common
    'common.save': 'Guardar Cambios',
    'common.cancel': 'Cancelar',
    'common.create': 'Crear',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.actions': 'Acciones',
    'common.viewAll': 'Ver todas',
    'common.export': 'Exportar',
    'common.exportPdf': 'Exportar PDF',
    
    // Dashboard
    'dashboard.welcome': 'Bienvenido',
    'dashboard.summary': 'Resumen de actividad y precios en tiempo real',
    'dashboard.newOrder': 'Nueva Orden',
    'dashboard.goldPrice': 'Precio del Oro',
    'dashboard.exchangeRate': 'Tasa de Cambio',
    'dashboard.totalOrders': 'Órdenes Totales',
    'dashboard.completed': 'Completadas',
    'dashboard.pending': 'Pendientes',
    'dashboard.totalGrams': 'Total Gramos',
    'dashboard.recentOrders': 'Órdenes Recientes',
    'dashboard.thisMonth': 'este mes',
    'dashboard.thisWeek': 'esta semana',
    
    // Orders
    'orders.title': 'Gestión de Órdenes',
    'orders.myOrders': 'Mis Órdenes',
    'orders.found': 'órdenes encontradas',
    'orders.searchProvider': 'Buscar por proveedor...',
    'orders.allStatuses': 'Todos los estados',
    'orders.pending': 'Pendientes',
    'orders.completed': 'Completadas',
    'orders.noOrders': 'No hay órdenes para mostrar',
    'orders.id': 'ID',
    'orders.provider': 'Proveedor',
    'orders.grams': 'Gramos',
    'orders.negotiation': '% Negociación',
    'orders.goldPrice': 'Precio Oro',
    'orders.dollarPrice': 'Precio Dólar',
    'orders.finalPrice': 'Precio Final',
    'orders.status': 'Estado',
    'orders.date': 'Fecha',
    'orders.statusCompleted': 'Completada',
    'orders.statusPending': 'Pendiente',
    
    // Deliveries
    'deliveries.title': 'Registro de Entregas',
    'deliveries.subtitle': 'Gestiona las entregas de oro por proveedor',
    'deliveries.new': 'Nueva Entrega',
    'deliveries.register': 'Registrar Entrega',
    'deliveries.registerDesc': 'Ingresa los datos de la nueva entrega de oro',
    'deliveries.provider': 'Proveedor',
    'deliveries.selectProvider': 'Seleccionar proveedor',
    'deliveries.quantity': 'Cantidad (gramos)',
    'deliveries.notes': 'Notas',
    'deliveries.notesPlaceholder': 'Observaciones de la entrega...',
    'deliveries.registerBtn': 'Registrar Entrega',
    'deliveries.success': 'Entrega registrada exitosamente',
    'deliveries.errorProvider': 'Seleccione un proveedor',
    'deliveries.totalDeliveries': 'Total Entregas',
    'deliveries.totalGrams': 'Total Gramos',
    'deliveries.activeProviders': 'Proveedores Activos',
    'deliveries.id': 'ID',
    'deliveries.date': 'Fecha',
    
    // Reports
    'reports.title': 'Reportes y Análisis',
    'reports.subtitle': 'Estadísticas detalladas de operaciones',
    'reports.allProviders': 'Todos los proveedores',
    'reports.totalValue': 'Valor Total Transado',
    'reports.totalGrams': 'Total Gramos',
    'reports.avgPrice': 'Precio Promedio/g',
    'reports.volumeChart': 'Volumen de Operaciones',
    'reports.providerChart': 'Valor por Proveedor (Millones COP)',
    
    // Login
    'login.welcome': 'Bienvenido',
    'login.subtitle': 'Ingresa tus credenciales para acceder a la plataforma',
    'login.email': 'Correo electrónico',
    'login.emailPlaceholder': 'tu@email.com',
    'login.password': 'Contraseña',
    'login.userType': 'Tipo de usuario',
    'login.admin': 'Administrador',
    'login.adminDesc': 'Acceso completo a todas las funcionalidades',
    'login.provider': 'Proveedor',
    'login.providerDesc': 'Negociación de precios y órdenes',
    'login.xquadra': 'Usuario Xquadra',
    'login.xquadraDesc': 'Registro de entregas y reportes',
    'login.enter': 'Ingresar',
    'login.entering': 'Ingresando...',
    'login.error': 'Credenciales inválidas. Use "demo123" como contraseña.',
    'login.demo': 'Demo:',
    'login.demoHint': 'Usa cualquier email y la contraseña',
    'login.tagline': 'Trading de',
    'login.taglineGold': 'Oro Premium',
    'login.platformDesc': 'Plataforma profesional para la negociación y gestión de transacciones de oro',
    
    // Users
    'users.title': 'Gestión de Usuarios',
    'users.subtitle': 'Administra los usuarios y sus permisos',
    'users.new': 'Nuevo Usuario',
    'users.edit': 'Editar Usuario',
    'users.create': 'Crear Nuevo Usuario',
    'users.editDesc': 'Modifica los datos del usuario.',
    'users.createDesc': 'Completa los datos para crear un nuevo usuario.',
    'users.fullName': 'Nombre Completo',
    'users.namePlaceholder': 'Nombre del usuario',
    'users.email': 'Correo Electrónico',
    'users.emailPlaceholder': 'correo@ejemplo.com',
    'users.role': 'Rol',
    'users.selectRole': 'Selecciona un rol',
    'users.roleAdmin': 'Administrador',
    'users.roleProvider': 'Proveedor',
    'users.roleXquadra': 'Usuario Xquadra',
    'users.password': 'Contraseña',
    'users.updated': 'Usuario actualizado',
    'users.updatedDesc': 'ha sido actualizado correctamente.',
    'users.created': 'Usuario creado',
    'users.createdDesc': 'ha sido creado correctamente.',
    'users.deleted': 'Usuario eliminado',
    'users.deletedDesc': 'ha sido eliminado correctamente.',
    'users.admins': 'Administradores',
    'users.providers': 'Proveedores',
    'users.xquadraUsers': 'Usuarios Xquadra',
    'users.systemUsers': 'Usuarios del Sistema',
    'users.systemUsersDesc': 'Lista de todos los usuarios registrados',
    'users.searchPlaceholder': 'Buscar por nombre o correo...',
    'users.filterRole': 'Filtrar por rol',
    'users.allRoles': 'Todos los roles',
    'users.user': 'Usuario',
    'users.status': 'Estado',
    'users.registrationDate': 'Fecha de Registro',
    'users.active': 'Activo',
    'users.inactive': 'Inactivo',
    'users.noResults': 'No se encontraron usuarios',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.orders': 'Orders',
    'nav.newOrder': 'New Order',
    'nav.myOrders': 'My Orders',
    'nav.negotiation': 'Negotiation',
    'nav.deliveries': 'Deliveries',
    'nav.providers': 'Providers',
    'nav.users': 'Users',
    // Providers page
    'providers.title': 'Provider Management',
    'providers.subtitle': 'Manage providers and their transactions',
    'providers.new': 'New Provider',
    'providers.edit': 'Edit Provider',
    'providers.create': 'Create New Provider',
    'providers.editDesc': 'Modify the provider details.',
    'providers.createDesc': 'Complete the details to register a new provider.',
    'providers.name': 'Provider Name',
    'providers.namePlaceholder': 'E.g: Mining Corp',
    'providers.email': 'Email Address',
    'providers.emailPlaceholder': 'email@example.com',
    'providers.updated': 'Provider updated',
    'providers.updatedDesc': 'has been updated successfully.',
    'providers.created': 'Provider created',
    'providers.createdDesc': 'has been registered successfully.',
    'providers.deleted': 'Provider deleted',
    'providers.deletedDesc': 'has been deleted successfully.',
    'providers.totalProviders': 'Total Providers',
    'providers.totalOrders': 'Total Orders',
    'providers.totalBalance': 'Total Balance',
    'providers.list': 'Provider List',
    'providers.listDesc': 'All registered providers in the system',
    'providers.search': 'Search by name or email...',
    'providers.provider': 'Provider',
    'providers.orders': 'Orders',
    'providers.deliveries': 'Deliveries',
    'providers.balance': 'Balance',
    'providers.actions': 'Actions',
    'providers.noResults': 'No providers found',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.logout': 'Log Out',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account and system preferences',
    'settings.profile': 'Profile',
    'settings.notifications': 'Notifications',
    'settings.api': 'APIs',
    'settings.security': 'Security',
    'settings.language': 'Language',
    
    // Profile
    'profile.title': 'Profile Information',
    'profile.description': 'Update your personal and contact information',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email Address',
    'profile.company': 'Company',
    'profile.phone': 'Phone',
    'profile.save': 'Save Changes',
    'profile.updated': 'Profile updated',
    'profile.updatedDesc': 'Your changes have been saved successfully.',
    
    // Notifications
    'notifications.title': 'Notification Preferences',
    'notifications.description': 'Configure how and when to receive notifications',
    'notifications.email': 'Email Notifications',
    'notifications.push': 'Push Notifications',
    'notifications.newOrders': 'New orders',
    'notifications.newOrdersDesc': 'Receive an email when a new order is created',
    'notifications.deliveries': 'Registered deliveries',
    'notifications.deliveriesDesc': 'Notification when a delivery is registered',
    'notifications.weeklyReports': 'Weekly reports',
    'notifications.weeklyReportsDesc': 'Weekly activity summary',
    'notifications.orderAlerts': 'Order alerts',
    'notifications.orderAlertsDesc': 'Real-time order notifications',
    'notifications.deliveryAlerts': 'Delivery alerts',
    'notifications.deliveryAlertsDesc': 'Real-time delivery notifications',
    'notifications.save': 'Save Preferences',
    'notifications.updated': 'Notifications updated',
    'notifications.updatedDesc': 'Your notification preferences have been saved.',
    
    // API
    'api.title': 'API Configuration',
    'api.description': 'Manage credentials for live price APIs',
    'api.goldKey': 'API Key - Gold Price',
    'api.goldKeyPlaceholder': 'Your GoldAPI key',
    'api.goldKeyHelp': 'Get it at goldapi.io',
    'api.dollarKey': 'API Key - Exchange Rate',
    'api.dollarKeyPlaceholder': 'Your ExchangeRate API key',
    'api.dollarKeyHelp': 'Get it at exchangerate-api.com',
    'api.refreshInterval': 'Refresh interval (seconds)',
    'api.refreshIntervalHelp': 'Price update frequency (min: 10s)',
    'api.testConnection': 'Test Connection',
    'api.save': 'Save APIs',
    'api.saved': 'API configuration saved',
    'api.savedDesc': 'API credentials have been updated.',
    
    // Security
    'security.title': 'Account Security',
    'security.description': 'Manage your account security and access',
    'security.changePassword': 'Change Password',
    'security.currentPassword': 'Current Password',
    'security.newPassword': 'New Password',
    'security.confirmPassword': 'Confirm Password',
    'security.activeSessions': 'Active Sessions',
    'security.currentSession': 'Current session',
    'security.location': 'Chrome on Windows • Bogotá, Colombia',
    'security.active': 'Active',
    'security.updatePassword': 'Update Password',
    
    // Language
    'language.title': 'Language Preferences',
    'language.description': 'Select the interface language',
    'language.select': 'Interface language',
    'language.spanish': 'Spanish',
    'language.english': 'English',
    'language.save': 'Save Language',
    'language.saved': 'Language updated',
    'language.savedDesc': 'The interface language has been changed.',
    
    // Common
    'common.save': 'Save Changes',
    'common.cancel': 'Cancel',
    'common.create': 'Create',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.actions': 'Actions',
    'common.viewAll': 'View all',
    'common.export': 'Export',
    'common.exportPdf': 'Export PDF',
    
    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.summary': 'Activity summary and real-time prices',
    'dashboard.newOrder': 'New Order',
    'dashboard.goldPrice': 'Gold Price',
    'dashboard.exchangeRate': 'Exchange Rate',
    'dashboard.totalOrders': 'Total Orders',
    'dashboard.completed': 'Completed',
    'dashboard.pending': 'Pending',
    'dashboard.totalGrams': 'Total Grams',
    'dashboard.recentOrders': 'Recent Orders',
    'dashboard.thisMonth': 'this month',
    'dashboard.thisWeek': 'this week',
    
    // Orders
    'orders.title': 'Order Management',
    'orders.myOrders': 'My Orders',
    'orders.found': 'orders found',
    'orders.searchProvider': 'Search by provider...',
    'orders.allStatuses': 'All statuses',
    'orders.pending': 'Pending',
    'orders.completed': 'Completed',
    'orders.noOrders': 'No orders to display',
    'orders.id': 'ID',
    'orders.provider': 'Provider',
    'orders.grams': 'Grams',
    'orders.negotiation': 'Negotiation %',
    'orders.goldPrice': 'Gold Price',
    'orders.dollarPrice': 'Dollar Price',
    'orders.finalPrice': 'Final Price',
    'orders.status': 'Status',
    'orders.date': 'Date',
    'orders.statusCompleted': 'Completed',
    'orders.statusPending': 'Pending',
    
    // Deliveries
    'deliveries.title': 'Delivery Records',
    'deliveries.subtitle': 'Manage gold deliveries by provider',
    'deliveries.new': 'New Delivery',
    'deliveries.register': 'Register Delivery',
    'deliveries.registerDesc': 'Enter the details of the new gold delivery',
    'deliveries.provider': 'Provider',
    'deliveries.selectProvider': 'Select provider',
    'deliveries.quantity': 'Quantity (grams)',
    'deliveries.notes': 'Notes',
    'deliveries.notesPlaceholder': 'Delivery observations...',
    'deliveries.registerBtn': 'Register Delivery',
    'deliveries.success': 'Delivery registered successfully',
    'deliveries.errorProvider': 'Please select a provider',
    'deliveries.totalDeliveries': 'Total Deliveries',
    'deliveries.totalGrams': 'Total Grams',
    'deliveries.activeProviders': 'Active Providers',
    'deliveries.id': 'ID',
    'deliveries.date': 'Date',
    
    // Reports
    'reports.title': 'Reports & Analytics',
    'reports.subtitle': 'Detailed operation statistics',
    'reports.allProviders': 'All providers',
    'reports.totalValue': 'Total Value Traded',
    'reports.totalGrams': 'Total Grams',
    'reports.avgPrice': 'Average Price/g',
    'reports.volumeChart': 'Operations Volume',
    'reports.providerChart': 'Value by Provider (Millions COP)',
    
    // Login
    'login.welcome': 'Welcome',
    'login.subtitle': 'Enter your credentials to access the platform',
    'login.email': 'Email address',
    'login.emailPlaceholder': 'your@email.com',
    'login.password': 'Password',
    'login.userType': 'User type',
    'login.admin': 'Administrator',
    'login.adminDesc': 'Full access to all features',
    'login.provider': 'Provider',
    'login.providerDesc': 'Price negotiation and orders',
    'login.xquadra': 'Xquadra User',
    'login.xquadraDesc': 'Delivery records and reports',
    'login.enter': 'Sign In',
    'login.entering': 'Signing in...',
    'login.error': 'Invalid credentials. Use "demo123" as password.',
    'login.demo': 'Demo:',
    'login.demoHint': 'Use any email and password',
    'login.tagline': 'Premium',
    'login.taglineGold': 'Gold Trading',
    'login.platformDesc': 'Professional platform for gold transaction negotiation and management',
    
    // Users
    'users.title': 'User Management',
    'users.subtitle': 'Manage users and their permissions',
    'users.new': 'New User',
    'users.edit': 'Edit User',
    'users.create': 'Create New User',
    'users.editDesc': 'Modify the user details.',
    'users.createDesc': 'Complete the details to create a new user.',
    'users.fullName': 'Full Name',
    'users.namePlaceholder': 'User name',
    'users.email': 'Email Address',
    'users.emailPlaceholder': 'email@example.com',
    'users.role': 'Role',
    'users.selectRole': 'Select a role',
    'users.roleAdmin': 'Administrator',
    'users.roleProvider': 'Provider',
    'users.roleXquadra': 'Xquadra User',
    'users.password': 'Password',
    'users.updated': 'User updated',
    'users.updatedDesc': 'has been updated successfully.',
    'users.created': 'User created',
    'users.createdDesc': 'has been created successfully.',
    'users.deleted': 'User deleted',
    'users.deletedDesc': 'has been deleted successfully.',
    'users.admins': 'Administrators',
    'users.providers': 'Providers',
    'users.xquadraUsers': 'Xquadra Users',
    'users.systemUsers': 'System Users',
    'users.systemUsersDesc': 'List of all registered users',
    'users.searchPlaceholder': 'Search by name or email...',
    'users.filterRole': 'Filter by role',
    'users.allRoles': 'All roles',
    'users.user': 'User',
    'users.status': 'Status',
    'users.registrationDate': 'Registration Date',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.noResults': 'No users found',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'es';
  });

  useEffect(() => {
    localStorage.setItem('app-language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
